#' Atlas Orthology Plotting Functions
#' 
#' This script provides functions to visualize gene trees generated by the 
#' Ensembl Orthology Pipeline, highlighting high-confidence (HQ) assignments.

library(tidyverse)
library(ape)
library(ggtree)
library(Biostrings)
library(ggmsa)
library(stringr)
library(msaR)
library(htmlwidgets)

# --- Path Configuration ---
# Update these if running from a different directory
MASTER_PATH <- "ensembl_pipeline_output/Consensus_Master.tsv"
ARCHIVE_PATH <- "ensembl_pipeline_output/Phylogenetic_Trees.tar.gz"
SPECIES_TREE_PATH <- "input/DB/species_tree.nwk"

# Default directories within archive
TREE_DIR_INT <- "Phylogenetic_Trees/Gene_Trees"
MSA_DIR_INT <- "Phylogenetic_Trees/MSAs"

#' Extract a specific file from the tar.gz archive to a temporary location
#' @param archive Path to the .tar.gz archive
#' @param internal_path Path within the archive (e.g., "Phylogenetic_Trees/MSAs/OG_00001.fa")
extract_from_archive <- function(archive = ARCHIVE_PATH, internal_path) {
  if (!file.exists(archive)) {
    stop("Archive not found: ", archive)
  }
  
  # Ensure internal path uses forward slashes
  internal_path <- gsub("\\\\", "/", internal_path)
  
  temp_ex_dir <- tempdir()
  
  # Extract the specific file
  # We use the built-in untar. 
  untar(archive, files = internal_path, exdir = temp_ex_dir)
  
  actual_extracted_path <- file.path(temp_ex_dir, internal_path)
  
  if (file.exists(actual_extracted_path)) {
    return(actual_extracted_path)
  } else {
    return(NULL)
  }
}

#' Load and prepare the Master Table for plotting
load_master_for_plots <- function(path = MASTER_PATH) {
  if(!file.exists(path)) stop("Master table not found: ", path)
  df <- read_tsv(path, show_col_types = FALSE)
  return(df)
}

#' Root a gene tree using the standard species hierarchy
root_atlas_tree <- function(tree) {
  species_in_tree <- sub("_.*", "", tree$tip.label)
  # Rooting hierarchy priority
  hierarchy <- c("PIGXX", "RATNO", "MOUSE", "MACFA", "HUMAN")
  for (sp in hierarchy) {
    if (sp %in% species_in_tree) {
      # Handle case where the chosen outgroup might lead to invalid tree
      try({
        tree <- root(tree, outgroup = tree$tip.label[which(species_in_tree == sp)[1]], resolve.root = TRUE)
        break
      }, silent = TRUE)
    }
  }
  return(tree)
}

#' Plot an Atlas Gene Tree with HQ confidence indicators
#' @param og_id The simplified OG ID (e.g., "OG_00001")
#' @param master_df The loaded master consensus table
#' @param tree_path Path to the .nwk file (If NULL, extracts from ARCHIVE_PATH)
plot_atlas_tree <- function(og_id, master_df, tree_path = NULL) {
  
  actual_path <- tree_path
  is_temp <- FALSE
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    internal_path <- file.path(TREE_DIR_INT, paste0(og_id, ".nwk"))
    actual_path <- extract_from_archive(ARCHIVE_PATH, internal_path)
    is_temp <- TRUE
  }
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    message("Tree file not found for: ", og_id)
    return(NULL)
  }
  
  # Treerecs files often have a header line starting with '>'
  # We strip this to make it compatible with ape::read.tree
  lines <- readLines(actual_path, warn = FALSE)
  clean_lines <- lines[!startsWith(lines, ">")]
  
  tree <- read.tree(text = paste(clean_lines, collapse = ""))
  
  # Clean up temp file immediately after reading into memory
  if (is_temp) unlink(actual_path)
  
  if (is.null(tree)) return(NULL)
  
  tree <- root_atlas_tree(tree)
  
  # Extract Gene IDs from tips (Format: SPECIES_ENSID)
  tip_metadata <- tibble(label = tree$tip.label) %>%
    mutate(ensembl_id = sub("^[A-Z]+_", "", label)) %>%
    left_join(master_df, by = "ensembl_id")
  
  # Define Confidence
  tip_metadata <- tip_metadata %>%
    mutate(
      confidence = case_when(
        ens_hqorthogroup_status %in% c("1to1", "multi_copy") ~ "High Confidence",
        TRUE ~ "Low Confidence (HQ Singleton)"
      ),
      clean_symbol = ifelse(is.na(gene_symbol) | gene_symbol == "", ensembl_id, gene_symbol),
      display_label = paste0(species_code, "_", clean_symbol)
    )
  
  sp_cols <- c("HUMAN"="#E41A1C", "MACFA"="#377EB8", "MOUSE"="#4DAF4A", "RATNO"="#984EA3", "PIGXX"="#FF7F00")
  
  p <- ggtree(tree) %<+% tip_metadata +
    geom_tippoint(aes(color = species_code, shape = confidence), size = 3) +
    geom_tiplab(aes(label = display_label, color = species_code), size = 3, offset = 0.05) +
    theme_tree2() +
    scale_color_manual(values = sp_cols, name = "Species") +
    scale_shape_manual(values = c("High Confidence" = 16, "Low Confidence (HQ Singleton)" = 1), name = "HQ Track Status") +
    scale_x_continuous(expand = expansion(mult = 0.5)) +
    labs(
      title = paste("Gene Tree:", og_id),
      subtitle = "Solid circles indicate genes retained in the High-Confidence (HQ) track."
    )
  
  return(p)
}

#' Plot an Atlas MSA with relabeled sequences
#' @param og_id The simplified OG ID (e.g., "OG_00001")
#' @param master_df The loaded master consensus table
#' @param msa_path Path to the .fa (fasta) alignment file (If NULL, extracts from ARCHIVE_PATH)
#' @param start_pos Start coordinate for the plot window
#' @param end_pos End coordinate for the plot window
plot_atlas_msa <- function(og_id, master_df, msa_path = NULL, start_pos = 1, end_pos = 100) {
  
  actual_path <- msa_path
  is_temp <- FALSE
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    internal_path <- file.path(MSA_DIR_INT, paste0(og_id, ".fa"))
    actual_path <- extract_from_archive(ARCHIVE_PATH, internal_path)
    is_temp <- TRUE
  }
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    message("MSA file not found for: ", og_id)
    return(NULL)
  }
  
  aln <- readAAStringSet(actual_path)
  if (is_temp) unlink(actual_path)
  
  # Relabel sequences: Species_Symbol
  raw_names <- names(aln)
  extracted_ids <- sub("^[A-Z]+_", "", raw_names)
  
  # Join with metadata for symbols
  labels_df <- tibble(ensembl_id = extracted_ids, raw_name = raw_names) %>%
    left_join(master_df %>% select(ensembl_id, gene_symbol, species_code), by = "ensembl_id") %>%
    mutate(
      clean_symbol = ifelse(is.na(gene_symbol) | gene_symbol == "", ensembl_id, gene_symbol),
      new_label = paste0(species_code, "_", clean_symbol)
    )
  
  names(aln) <- make.unique(labels_df$new_label)
  
  p <- suppressWarnings(
    ggmsa(aln, start = start_pos, end = end_pos, color = "Clustal", seq_name = TRUE) +
    labs(title = paste("MSA Alignment:", og_id))
  )
  
  return(p)
}

#' Export an Atlas MSA as an interactive HTML widget
#' @param og_id The simplified OG ID (e.g., "OG_00001")
#' @param master_df The loaded master consensus table
#' @param msa_path Path to the .fa (fasta) alignment file (If NULL, extracts from ARCHIVE_PATH)
#' @param output_path Path to save the .html file
export_atlas_msa_html <- function(og_id, master_df, msa_path = NULL, output_path) {
  
  actual_path <- msa_path
  is_temp <- FALSE
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    internal_path <- file.path(MSA_DIR_INT, paste0(og_id, ".fa"))
    actual_path <- extract_from_archive(ARCHIVE_PATH, internal_path)
    is_temp <- TRUE
  }
  
  if (is.null(actual_path) || !file.exists(actual_path)) {
    message("MSA file not found for: ", og_id)
    return(NULL)
  }
  
  aln <- readAAStringSet(actual_path)
  if (is_temp) unlink(actual_path)
  
  # Relabel sequences: Species_Symbol
  raw_names <- names(aln)
  extracted_ids <- sub("^[A-Z]+_", "", raw_names)
  
  labels_df <- tibble(ensembl_id = extracted_ids, raw_name = raw_names) %>%
    left_join(master_df %>% select(ensembl_id, gene_symbol, species_code), by = "ensembl_id") %>%
    mutate(
      clean_symbol = ifelse(is.na(gene_symbol) | gene_symbol == "", ensembl_id, gene_symbol),
      new_label = paste0(species_code, "_", clean_symbol)
    )
  
  names(aln) <- make.unique(labels_df$new_label)
  
  # Create interactive widget
  widget <- msaR(aln, menu = TRUE, overviewbox = TRUE, seqlogo = TRUE)
  
  # Save to file
  saveWidget(widget, output_path, selfcontained = TRUE)
  message("  Interactive MSA saved to ", output_path)
  
  return(widget)
}
